# Generated by Django 4.1.3 on 2022-11-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveBigIntegerField(blank=True, choices=[(1, 'vendor'), (2, 'customer')], null=True),
        ),
    ]
